//Visualize WAF rule actions such as allowed, blocked, detected and matched over time

//Data connector required for this query - Azure Diagnostics (Application Gateways)

AzureDiagnostics
| where TimeGenerated > ago(30d)
| where ResourceType == "APPLICATIONGATEWAYS"
| summarize count()by action_s, bin(TimeGenerated, 1h)
| where isnotempty(action_s)
| render timechart with (ytitle="WAF Hit Count", title="Web application firewall traffic over time")