//Visualizes queries against your log analytics workspace categorized by users and service principals

//Data connector required for this query - Log Analytics diagnostic settings enabled on your Sentinel workspace

let timeframe=45d;
LAQueryLogs
| where TimeGenerated > ago (timeframe)
| summarize Users=countif(isnotempty(AADEmail)), Playbooks=countif(isempty(AADEmail)) by bin(TimeGenerated, 1d)
| render columnchart with (kind=unstacked, ytitle="Queries Run", title="Queries Run - Users vs Playbooks") 