//Find which users have attempted to connect to virtual machines using RDP or SSH in Azure Bastion

//Data connector required for this query - Azure Bastion

MicrosoftAzureBastionAuditLogs
| parse TargetResourceId with * 'VIRTUALMACHINES/' ['Virtual Machine Name']
| project
    TimeGenerated,
    Message,
    UserName,
    Protocol,
    ['Virtual Machine Name'],
    ['Virtual Machine IP']=TargetVMIPAddress
| sort by TimeGenerated desc 