//Detect when a new credential is added to an Azure AD application registration
AuditLogs
| where OperationName has "Update application – Certificates and secrets management"
| extend ApplicationName = tostring(TargetResources[0].displayName)
| extend ApplicationObjectId = tostring(TargetResources[0].id)
| extend Actor = tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName)
| extend ActorIPAddress = tostring(parse_json(tostring(InitiatedBy.user)).ipAddress)
| project TimeGenerated, ApplicationName, ApplicationObjectId, Actor, ActorIPAddress